title:              Glerf
email:              your-email@example.com
description:        I’m a digital artist from Buenos Aires, Argentina. I love to explore my style and skills with 2D concept art, pixel art and sometimes other art mediums. Here I have everything I have to offer as an artist, as well as my passions and personal interests.
author:             Guadalupe Ferreira Le Roi
baseurl:            ""
url:                "https://glerf.art"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
